// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeamStatusData.Data;

#nullable disable

namespace TeamStatusData.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeamStatusData.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Users", "teamstatus");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "McKenzie Powell",
                            Status = 0,
                            Title = "ISM Manager"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Sakura Crandall",
                            Status = 4,
                            Title = "ISM"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Brittany Mercedes",
                            Status = 0,
                            Title = "ISM"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Ryan Vidlak",
                            Status = 0,
                            Title = "ISM"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Grace le Bleu",
                            Status = 0,
                            Title = "ISM"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Dan Walls",
                            Status = 5,
                            Title = "ISM"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Tim O'Malley",
                            Status = 1,
                            Title = "Sales Manager III"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Daniel Clogston",
                            Status = 1,
                            Title = "Sales Manager III"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Sam Mowrer",
                            Status = 3,
                            Title = "Pretend ISM"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Kingsley Adragna",
                            Status = 2,
                            Title = "ISM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
